<div class="footer-col">
	<h4>¿Por qué comprar ?</h4>
	<div class="footer-col-content">
		<ul>
			<li><a href="#">Envíos y Devoluciones</a></li>
			<li><a href="#">Compras Seguras</a></li>
			<li><a href="#">Envío internacional</a></li>
			<li><a href="#">Afiliados</a></li>
			<li><a href="#">Ventas de Grupo</a></li>
		</ul>
	</div>
</div>
<div class="footer-col">
<h4>MI CUENTA</h4>
	<div class="footer-col-content">
		<ul>
			<li><a href="{{store url='customer/account/login/'}}">Inicia sesión</a></li>
			<li><a href="{{store url='checkout/cart/'}}">Ver Carrito</a></li>
			<li><a href="{{store url='wishlist/'}}">Mi lista de deseos</a></li>
			<li><a href="#">Estado de mi pedido</a></li>
			<li><a href="#">Ayuda</a></li>
		</ul>
	</div>
</div>
<div class="footer-col">
	<h4>Store Location</h4>
	<div class="footer-col-content">
		<ul class="contacts">
			<li>Store Location 8901</li>
			<li>Marmora Road,</li>
			<li>Glasgow,  D04 89GR</li>
		</ul>
		<h4>Order online</h4>
		Tel:1(234) 567-8902
	</div>
</div>
