<div class="footer-col">
	<h4>Warum bei uns kaufen</h4>
	<div class="footer-col-content">
		<ul>
			<li><a href="#">Liefer-und Versandkosten</a></li>
			<li><a href="#">Sicheres Einkaufen</a></li>
			<li><a href="#">Internationaler Versand</a></li>
			<li><a href="#">Affiliates</a></li>
			<li><a href="#">Group Sales</a></li>
		</ul>
	</div>
</div>
<div class="footer-col">
<h4>Mein konto<h4>
	<div class="footer-col-content">
		<ul>
			<li><a href="{{store url='customer/account/login/'}}">Anmelden</a></li>
			<li><a href="{{store url='checkout/cart/'}}">Warenkorb anzeigen</a></li>
			<li><a href="{{store url='wishlist/'}}">Mein Wunschzettel</a></li>
			<li><a href="#">Meine Bestellung verfolgen</a></li>
			<li><a href="#">Hilfe</a></li>
		</ul>
	</div>
</div>
<div class="footer-col">
	<h4>Store Location</h4>
	<div class="footer-col-content">
		<ul class="contacts">
			<li>Store Location 8901</li>
			<li>Marmora Road,</li>
			<li>Glasgow,  D04 89GR</li>
		</ul>
		<h4>Order online</h4>
		Tel:1(234) 567-8902
	</div>
</div>
