<div class="footer-col">
	<h4>Почему стоит купить</h4>
	<div class="footer-col-content">
		<ul>
			<li><a href="#">Доставка и возврат</a></li>
			<li><a href="#">Безопасные покупки</a></li>
			<li><a href="#">Международные перевозки</a></li>
			<li><a href="#">Партнеры</a></li>
			<li><a href="#">Группа продаж</a></li>
		</ul>
	</div>
</div>
<div class="footer-col">
<h4>Мой акаунт</h4>
	<div class="footer-col-content">
		<ul>
			<li><a href="{{store url='customer/account/login/'}}">Войти</a></li>
			<li><a href="{{store url='checkout/cart/'}}">Просмотр корзины</a></li>
			<li><a href="{{store url='wishlist/'}}">Мои предпочтения</a></li>
			<li><a href="#">Мой заказ</a></li>
			<li><a href="#">Помощь</a></li>
		</ul>
	</div>
</div>
<div class="footer-col">
	<h4>Store Location</h4>
	<div class="footer-col-content">
		<ul class="contacts">
			<li>Store Location 8901</li>
			<li>Marmora Road,</li>
			<li>Glasgow,  D04 89GR</li>
		</ul>
		<h4>Order online</h4>
		Tel:1(234) 567-8902
	</div>
</div>
