<ul class="header-menu">
<li><a href="{{store direct_url=''}}">Casa</a></li>
<li><a href="{{store direct_url='about-magento-demo-store'}}">Acerca</a></li>
<li><a href="{{store direct_url='customer-service'}}">Servicio al Cliente</a></li>
<li><a href="{{store direct_url='catalog/seo_sitemap/category/'}}">Mapa</a></li>
<li><a href="{{store direct_url='catalogsearch/advanced/'}}">Busqueda Avanzada</a></li>
<li><a href="{{store direct_url='contacts/'}}">Contacte</a></li>
</ul>