<ul class="header-menu">
<li><a href="{{store direct_url=''}}">Home</a></li>
<li><a href="{{store direct_url='about-magento-demo-store'}}">About Us</a></li>
<li><a href="{{store direct_url='customer-service'}}">Customer Service</a></li>
<li><a href="{{store direct_url='catalog/seo_sitemap/category/'}}">Site Map</a></li>
<li><a href="{{store direct_url='catalogsearch/advanced/'}}">Advanced Search</a></li>
<li><a href="{{store direct_url='contacts/'}}">Contact Us</a></li>
</ul>