<ul class="header-menu">
<li><a href="{{store direct_url=''}}">Домой</a></li>
<li><a href="{{store direct_url='about-magento-demo-store'}}">О компании</a></li>
<li><a href="{{store direct_url='customer-service'}}">Обслуживание клиентов</a></li>
<li><a href="{{store direct_url='catalog/seo_sitemap/category/'}}">Карта сайта</a></li>
<li><a href="{{store direct_url='catalogsearch/advanced/'}}"> поиск</a></li>
<li><a href="{{store direct_url='contacts/'}}">Обратна связь</a></li>
</ul>