<ul class="header-menu">
<li><a href="{{store direct_url=''}}">Hause</a></li>
<li><a href="{{store direct_url='about-magento-demo-store'}}">Wir uber uns</a></li>
<li><a href="{{store direct_url='customer-service'}}">Kundenservice</a></li>
<li><a href="{{store direct_url='catalog/seo_sitemap/category/'}}">Site Map</a></li>
<li><a href="{{store direct_url='catalogsearch/advanced/'}}">Erweiterte Suche</a></li>
<li><a href="{{store direct_url='contacts/'}}">Kontaktieren Sie uns</a></li>
</ul>