<script type="text/javascript" src="{{skin url='js/tms-0.4.1.js'}}"> </script>
<script type="text/javascript" src="{{skin url='js/jquery.easing.1.3.js'}}"></script>
<script type="text/javascript">
       jQuery(window).load(function() {
          jQuery('.slider')._TMS({
			duration:800,
			easing:'easeOutQuad',
			preset:'simpleFade',
			pagination:'.pagination',
		    slideshow:8000,
			banners:'fade',
			waitBannerAnimation:false,
			pauseOnHover:true
	   		});

		}); 
	</script>
<div class="slider-bg">
     <div class="slider-wrapper">
        <div class="slider">
            <ul class="items">
                <li>
                    <img src="{{skin url='images/media/slider1.png'}}" alt=""  />
                    <div class="banner">
                         	<a class="link-extra" href="{{store url='#'}}">Shop Now!</a>
                    </div>
                </li>
                <li>
                    <img src="{{skin url='images/media/slider2.png'}}" alt=""  />
                    <div class="banner">
                         	<a class="link-extra" href="{{store url='#'}}">Shop Now!</a>
                    </div>
                </li>
                <li>
                    <img src="{{skin url='images/media/slider3.png'}}" alt=""  />
                    <div class="banner">
                         	<a class="link-extra" href="{{store url='#'}}">Shop Now!</a>
                    </div>
                </li>
            </ul>
        </div> 
         <ul class="pagination">
          <li><a href="{{store url='#'}}">1</a></li>
          <li><a href="{{store url='#'}}">2</a></li>
          <li><a href="{{store url='#'}}">3</a></li>
      </ul>
    </div>
	  <div class="banner-top">
	      <a class="banner-block-1" href="{{store url='#'}}"><img src="{{skin url='images/media/banners-1.png'}}" alt=""  /></a>
	      <a class="banner-block-2" href="{{store url='#'}}"><img src="{{skin url='images/media/banners-2.png'}}" alt=""  /></a>
	      <a class="banner-block-3" href="{{store url='#'}}"><img src="{{skin url='images/media/banners-3.png'}}" alt=""  /></a>
	  <a class="banner-block-3" href="{{store url='#'}}"><img src="{{skin url='images/media/banners-4.png'}}" alt=""  /></a>
	  </div>
</div>
<div class="clear"></div>