<div class="fluid_container">
	<div class="camera_wrap camera_orange_skin" id="camera_wrap">
		<div data-link="{{store url='appetizers.html'}}"  data-thumb="{{skin url='images/camera/slides/thumbs/slide1-thumb.png'}}" data-src="{{skin url='images/camera/slides/slide1.jpg'}}"></div>
		<div data-link="{{store url='desserts.html'}}" data-thumb="{{skin url='images/camera/slides/thumbs/slide2-thumb.png'}}" data-src="{{skin url='images/camera/slides/slide2.jpg'}}"></div>
		<div data-link="{{store url='meat.html'}}" data-thumb="{{skin url='images/camera/slides/thumbs/slide3-thumb.png'}}" data-src="{{skin url='images/camera/slides/slide3.jpg'}}"></div>
		<div data-link="{{store url='seafood.html'}}" data-thumb="{{skin url='images/camera/slides/thumbs/slide4-thumb.png'}}" data-src="{{skin url='images/camera/slides/slide3.jpg'}}"></div>
	</div>
</div>


<div class="banners-block">
	<div class="main-banner num-1">
		<a href="{{store url='snacks.html'}}"><img title="" alt="" src="{{skin url='images/banner-1.jpg'}}"></a>
	</div>          
	<div class="main-banner num-2">
		<a href="{{store url='fruits-vegetable/fruits.html'}}"><img title="" alt="" src="{{skin url='images/banner-2.jpg'}}"></a>
	</div>          
	<div class="main-banner num-3">
		<a href="{{store url='fruits-vegetable/vegetable.html'}}"><img title="" alt="" src="{{skin url='images/banner-3.jpg'}}"></a>
	</div>
</div>